
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 27 2024 03:11:18

// Verification Directory fv/synth_wrapper 

module synth_wrapper(a, b, op, rst_n, clk, result, carry);
  input [3:0] a, b;
  input [2:0] op;
  input rst_n, clk;
  output [3:0] result;
  output carry;
  wire [3:0] a, b;
  wire [2:0] op;
  wire rst_n, clk;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire n_1, n_5, n_14, n_26, n_35, n_37, n_39, n_47;
  wire n_50, n_52, n_55, n_61, n_66, n_72, n_74, n_80;
  wire n_88, n_93, n_98, n_99, n_100, n_104, n_110, n_111;
  wire n_118, n_122, n_135, n_142, n_150, n_153, n_157, n_159;
  wire n_161, n_164, n_165, n_169, n_170, n_173, n_175, n_177;
  wire n_213, n_214, n_216, n_217, n_234, n_235, n_237, n_248;
  wire n_254, n_255, n_256, n_257, n_261, n_289, n_292, n_293;
  wire n_294, n_295, n_296, n_321, n_323, n_324, n_327, n_329;
  wire n_330, n_333, n_334, n_336, n_362, n_363, n_369, n_376;
  wire n_379, n_380, n_381, n_382, n_415, n_417, n_419, n_436;
  wire n_439, n_457, n_459, n_467, n_480, n_493, n_494, n_496;
  wire n_497, n_499, n_500, n_517, n_519, n_536, n_540, n_541;
  wire n_542, n_545, n_547, n_550, n_553, n_555, n_557, n_559;
  wire n_560, n_561, n_566, n_567, n_602, n_609, n_617, n_618;
  wire n_619, n_622, n_623, n_627, n_628, n_629, n_631, n_632;
  wire n_637, n_641, n_642, n_643, n_644, n_645, n_646, n_647;
  wire n_652, n_653, n_654, n_691, n_692, n_695, n_697, n_722;
  wire n_723, n_726, n_727, n_728, n_729, n_730, n_731, n_733;
  wire n_735, n_737, n_738, n_740, n_741, n_742, n_744, n_745;
  wire n_746, n_747, n_748, n_749, n_752, n_753, n_754, n_755;
  wire n_756, n_757, n_758, n_759, n_760, n_761, n_762, n_765;
  wire n_766, n_767, n_768, n_769, n_770, n_771, n_772, n_773;
  wire n_774, n_775, n_776, n_777, n_779, n_780, n_787, n_799;
  wire n_801, n_952, n_953, n_954, n_955, n_956, n_957, n_994;
  wire n_995;
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (n_766), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (n_652), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (n_175), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (n_177), .Q (carry));
  sky130_fd_sc_hd__nand2_1 g16535(.A (n_169), .B (n_164), .Y (n_177));
  sky130_fd_sc_hd__nand2_1 g16537(.A (n_170), .B (n_173), .Y (n_175));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (n_161), .Q (result[0]));
  sky130_fd_sc_hd__nand2_1 g16540(.A (n_748), .B (n_733), .Y (n_173));
  sky130_fd_sc_hd__a21oi_2 g16543(.A1 (n_157), .A2 (n_362), .B1
       (n_727), .Y (n_170));
  sky130_fd_sc_hd__a21o_1 g16544(.A1 (n_692), .A2 (n_118), .B1 (n_1),
       .X (n_169));
  sky130_fd_sc_hd__inv_1 g16548(.A (n_745), .Y (n_165));
  sky130_fd_sc_hd__a21oi_2 g16549(.A1 (n_256), .A2 (n_737), .B1
       (n_104), .Y (n_164));
  sky130_fd_sc_hd__o21ai_1 g16552(.A1 (n_545), .A2 (n_362), .B1
       (n_954), .Y (n_161));
  sky130_fd_sc_hd__nand2_1 g16554(.A (n_142), .B (n_100), .Y (n_159));
  sky130_fd_sc_hd__nand3_1 g16556(.A (n_730), .B (n_787), .C (n_135),
       .Y (n_157));
  sky130_fd_sc_hd__o211a_1 g16559(.A1 (n_72), .A2 (n_98), .B1 (n_122),
       .C1 (n_729), .X (n_153));
  sky130_fd_sc_hd__nand2b_1 g16564(.A_N (n_100), .B (n_697), .Y
       (n_150));
  sky130_fd_sc_hd__nand3_1 g16576(.A (n_110), .B (n_561), .C (n_642),
       .Y (n_142));
  sky130_fd_sc_hd__nand2_1 g16587(.A (n_321), .B (n_566), .Y (n_135));
  sky130_fd_sc_hd__o22a_1 g16602(.A1 (n_436), .A2 (n_602), .B1 (n_757),
       .B2 (n_519), .X (n_122));
  sky130_fd_sc_hd__inv_2 g16607(.A (n_645), .Y (n_118));
  sky130_fd_sc_hd__nand3_1 g16615(.A (n_799), .B (n_329), .C (n_52), .Y
       (n_111));
  sky130_fd_sc_hd__nand2_1 g16616(.A (n_257), .B (n_695), .Y (n_110));
  sky130_fd_sc_hd__and3_1 g16624(.A (n_257), .B (n_52), .C (a_reg[3]),
       .X (n_104));
  sky130_fd_sc_hd__inv_2 g16638(.A (n_330), .Y (n_35));
  sky130_fd_sc_hd__nand2_1 g16640(.A (n_994), .B (n_52), .Y (n_93));
  sky130_fd_sc_hd__and2_1 g16643(.A (n_757), .B (n_774), .X (n_100));
  sky130_fd_sc_hd__nand2_2 g16646(.A (n_517), .B (n_293), .Y (n_99));
  sky130_fd_sc_hd__nand3_1 g16647(.A (n_329), .B (n_50), .C (n_777), .Y
       (n_98));
  sky130_fd_sc_hd__nor2_1 g16658(.A (n_380), .B (n_776), .Y (n_80));
  sky130_fd_sc_hd__nand2_2 g16661(.A (n_415), .B (n_296), .Y (n_88));
  sky130_fd_sc_hd__inv_2 g16670(.A (n_772), .Y (n_74));
  sky130_fd_sc_hd__inv_1 g16671(.A (n_774), .Y (n_72));
  sky130_fd_sc_hd__nand2b_1 g16681(.A_N (a_reg[3]), .B (b_reg[3]), .Y
       (n_66));
  sky130_fd_sc_hd__nand2_1 g16700(.A (n_617), .B (n_436), .Y (n_55));
  sky130_fd_sc_hd__nand2_1 g16707(.A (n_26), .B (a_reg[3]), .Y (n_61));
  sky130_fd_sc_hd__inv_1 g16713(.A (n_26), .Y (n_52));
  sky130_fd_sc_hd__inv_2 g16714(.A (b_reg[3]), .Y (n_26));
  sky130_fd_sc_hd__inv_4 g16720(.A (n_362), .Y (n_50));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (b[3]), .Q (b_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (a[0]), .Q (a_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op[0]), .Q (op_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (a[2]), .Q (a_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (b[0]), .Q (n_47));
  sky130_fd_sc_hd__dfrtp_2 \op_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op[1]), .Q (op_reg[1]));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (a[3]), .Q (a_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \op_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op[2]), .Q (n_39));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (a[1]), .Q (a_reg[1]));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (b[1]), .Q (b_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (b[2]), .Q (n_37));
  sky130_fd_sc_hd__buf_1 drc_bufs16799(.A (n_293), .X (n_14));
  sky130_fd_sc_hd__nand3b_2 g16843(.A_N (n_99), .B (n_632), .C (n_362),
       .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g16847(.A (n_61), .B (n_35), .Y (n_1));
  sky130_fd_sc_hd__nand2_1 g16852(.A (n_762), .B (n_295), .Y (n_213));
  sky130_fd_sc_hd__nand3_1 g16853(.A (n_376), .B (n_436), .C (n_617),
       .Y (n_214));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (n_217), .X (n_216));
  sky130_fd_sc_hd__clkbuf_1 fopt16855(.A (n_294), .X (n_217));
  sky130_fd_sc_hd__clkinv_1 fopt16867(.A (n_235), .Y (n_234));
  sky130_fd_sc_hd__clkbuf_2 fopt16868(.A (a_reg[0]), .X (n_235));
  sky130_fd_sc_hd__inv_2 fopt16869(.A (a_reg[0]), .Y (n_237));
  sky130_fd_sc_hd__o21ai_1 g16878(.A1 (n_363), .A2 (n_799), .B1
       (n_955), .Y (n_248));
  sky130_fd_sc_hd__o22a_1 g16884(.A1 (n_775), .A2 (n_261), .B1 (n_217),
       .B2 (n_255), .X (n_254));
  sky130_fd_sc_hd__nor2_2 g16885(.A (n_118), .B (n_255), .Y (n_256));
  sky130_fd_sc_hd__inv_2 g16887(.A (n_255), .Y (n_257));
  sky130_fd_sc_hd__nand3_1 g16888(.A (n_74), .B (n_780), .C (n_289), .Y
       (n_261));
  sky130_fd_sc_hd__nand4_1 g16921(.A (n_289), .B (n_780), .C (n_379),
       .D (n_329), .Y (n_292));
  sky130_fd_sc_hd__clkbuf_2 g16922(.A (n_336), .X (n_289));
  sky130_fd_sc_hd__nor2_2 g16923(.A (b_reg[3]), .B (n_336), .Y (n_293));
  sky130_fd_sc_hd__nand2_2 g16924(.A (n_336), .B (n_381), .Y (n_294));
  sky130_fd_sc_hd__nor2_1 g16925(.A (n_237), .B (n_336), .Y (n_295));
  sky130_fd_sc_hd__nand2_1 g16926(.A (n_382), .B (n_336), .Y (n_296));
  sky130_fd_sc_hd__nor2_2 g16953(.A (n_619), .B (n_99), .Y (n_321));
  sky130_fd_sc_hd__nand2_1 g16955(.A (n_321), .B (n_323), .Y (n_324));
  sky130_fd_sc_hd__and2_1 g16956(.A (n_547), .B (a_reg[3]), .X (n_323));
  sky130_fd_sc_hd__inv_2 g16962(.A (n_327), .Y (n_329));
  sky130_fd_sc_hd__nand3_2 g16963(.A (n_50), .B (n_777), .C (n_327), .Y
       (n_330));
  sky130_fd_sc_hd__buf_1 g16967(.A (n_333), .X (n_334));
  sky130_fd_sc_hd__inv_2 g16968(.A (n_37), .Y (n_333));
  sky130_fd_sc_hd__inv_4 g16969(.A (n_333), .Y (n_336));
  sky130_fd_sc_hd__inv_4 g16996(.A (op_reg[1]), .Y (n_327));
  sky130_fd_sc_hd__inv_4 g16997(.A (op_reg[0]), .Y (n_362));
  sky130_fd_sc_hd__nand2_4 g16998(.A (n_363), .B (n_777), .Y (n_255));
  sky130_fd_sc_hd__and2_4 g16999(.A (n_327), .B (n_362), .X (n_363));
  sky130_fd_sc_hd__nand4_1 g17003(.A (n_80), .B (n_773), .C (n_774), .D
       (n_74), .Y (n_369));
  sky130_fd_sc_hd__inv_4 fopt17010(.A (n_494), .Y (n_376));
  sky130_fd_sc_hd__inv_1 fopt17012(.A (n_380), .Y (n_379));
  sky130_fd_sc_hd__clkinv_1 fopt17013(.A (n_381), .Y (n_380));
  sky130_fd_sc_hd__inv_2 fopt17014(.A (n_381), .Y (n_382));
  sky130_fd_sc_hd__buf_6 fopt17015(.A (a_reg[2]), .X (n_381));
  sky130_fd_sc_hd__nand2_2 g17049(.A (n_381), .B (n_334), .Y (n_415));
  sky130_fd_sc_hd__inv_2 g17050(.A (n_500), .Y (n_419));
  sky130_fd_sc_hd__nand3_1 g17053(.A (n_493), .B (n_436), .C (n_617),
       .Y (n_417));
  sky130_fd_sc_hd__inv_1 fopt17074(.A (n_436), .Y (n_439));
  sky130_fd_sc_hd__and2_1 g17093(.A (n_553), .B (n_617), .X (n_459));
  sky130_fd_sc_hd__o22a_1 g17115(.A1 (n_235), .A2 (n_602), .B1 (n_695),
       .B2 (n_519), .X (n_480));
  sky130_fd_sc_hd__clkinv_4 g17129(.A (n_336), .Y (n_493));
  sky130_fd_sc_hd__clkinv_4 fopt17130(.A (n_381), .Y (n_494));
  sky130_fd_sc_hd__nand4_1 g17132(.A (n_496), .B (n_780), .C (n_50), .D
       (n_329), .Y (n_497));
  sky130_fd_sc_hd__nand2_1 g17133(.A (n_493), .B (n_494), .Y (n_496));
  sky130_fd_sc_hd__nand3_2 g17134(.A (n_499), .B (n_417), .C (n_415),
       .Y (n_500));
  sky130_fd_sc_hd__nand4_1 g1(.A (n_762), .B (n_457), .C (n_493), .D
       (n_494), .Y (n_499));
  sky130_fd_sc_hd__inv_2 fopt17135(.A (n_771), .Y (n_457));
  sky130_fd_sc_hd__clkinv_1 fopt17152(.A (n_994), .Y (n_519));
  sky130_fd_sc_hd__nor2_1 g17168(.A (n_362), .B (n_776), .Y (n_536));
  sky130_fd_sc_hd__nand2_1 g17173(.A (n_376), .B (n_457), .Y (n_540));
  sky130_fd_sc_hd__nand2_1 g17175(.A (n_540), .B (n_541), .Y (n_542));
  sky130_fd_sc_hd__nand2_1 g17176(.A (n_771), .B (a_reg[3]), .Y
       (n_541));
  sky130_fd_sc_hd__a21boi_1 g17177(.A1 (n_542), .A2 (n_321), .B1_N
       (n_787), .Y (n_545));
  sky130_fd_sc_hd__inv_2 fopt17182(.A (n_467), .Y (n_547));
  sky130_fd_sc_hd__nand2b_1 g17187(.A_N (n_555), .B (n_35), .Y (n_557));
  sky130_fd_sc_hd__nand2_4 g17189(.A (n_237), .B (n_553), .Y (n_555));
  sky130_fd_sc_hd__nand2_1 g17192(.A (n_555), .B (n_762), .Y (n_559));
  sky130_fd_sc_hd__nand3b_1 g17193(.A_N (n_294), .B (n_762), .C
       (n_555), .Y (n_560));
  sky130_fd_sc_hd__nand2_1 g17194(.A (n_35), .B (n_555), .Y (n_561));
  sky130_fd_sc_hd__nor2_1 g16705_dup17198(.A (n_234), .B (n_467), .Y
       (n_566));
  sky130_fd_sc_hd__buf_6 g17199(.A (n_771), .X (n_467));
  sky130_fd_sc_hd__o21ai_1 g17200(.A1 (n_467), .A2 (n_439), .B1
       (n_695), .Y (n_567));
  sky130_fd_sc_hd__nand3_2 g17235(.A (n_327), .B (n_779), .C (n_50), .Y
       (n_602));
  sky130_fd_sc_hd__nand2_1 g17244(.A (n_39), .B (op_reg[1]), .Y
       (n_609));
  sky130_fd_sc_hd__o21ai_2 g52(.A1 (n_619), .A2 (n_628), .B1 (n_631),
       .Y (n_632));
  sky130_fd_sc_hd__inv_2 g61(.A (n_618), .Y (n_619));
  sky130_fd_sc_hd__inv_2 g62(.A (n_617), .Y (n_618));
  sky130_fd_sc_hd__clkinv_4 g63(.A (b_reg[1]), .Y (n_617));
  sky130_fd_sc_hd__clkinv_1 g53(.A (n_627), .Y (n_628));
  sky130_fd_sc_hd__nand2_1 g54(.A (n_622), .B (n_761), .Y (n_627));
  sky130_fd_sc_hd__nand2_1 g57(.A (n_553), .B (a_reg[0]), .Y (n_622));
  sky130_fd_sc_hd__inv_4 g66(.A (n_770), .Y (n_553));
  sky130_fd_sc_hd__inv_2 g65(.A (n_553), .Y (n_623));
  sky130_fd_sc_hd__nand3_2 g55(.A (n_629), .B (n_553), .C (n_619), .Y
       (n_631));
  sky130_fd_sc_hd__inv_2 g59(.A (n_382), .Y (n_629));
  sky130_fd_sc_hd__nor2_2 g91(.A (n_330), .B (n_118), .Y (n_637));
  sky130_fd_sc_hd__inv_2 g14(.A (n_643), .Y (n_644));
  sky130_fd_sc_hd__nor2_2 g15(.A (n_641), .B (n_642), .Y (n_643));
  sky130_fd_sc_hd__and2_2 g17(.A (n_61), .B (n_66), .X (n_641));
  sky130_fd_sc_hd__nand2_2 g18(.A (n_773), .B (n_779), .Y (n_642));
  sky130_fd_sc_hd__inv_2 g16(.A (n_641), .Y (n_645));
  sky130_fd_sc_hd__inv_2 g17254(.A (n_646), .Y (n_647));
  sky130_fd_sc_hd__nand3_2 g17255(.A (n_760), .B (n_759), .C (n_369),
       .Y (n_646));
  sky130_fd_sc_hd__nand4_1 g17257(.A (n_754), .B (n_153), .C (n_159),
       .D (n_150), .Y (n_652));
  sky130_fd_sc_hd__a21oi_2 g51(.A1 (n_692), .A2 (n_637), .B1 (n_653),
       .Y (n_654));
  sky130_fd_sc_hd__nand4_2 g17258(.A (n_5), .B (n_644), .C (n_995), .D
       (n_111), .Y (n_653));
  sky130_fd_sc_hd__nand3_2 g29(.A (n_769), .B (n_254), .C (n_647), .Y
       (n_691));
  sky130_fd_sc_hd__nand2_2 g31(.A (n_768), .B (n_419), .Y (n_692));
  sky130_fd_sc_hd__o21ai_1 g20(.A1 (n_695), .A2 (n_255), .B1 (n_557),
       .Y (n_697));
  sky130_fd_sc_hd__nand2_2 g21(.A (n_553), .B (n_235), .Y (n_695));
  sky130_fd_sc_hd__nand3_2 g96(.A (n_723), .B (n_547), .C (n_517), .Y
       (n_550));
  sky130_fd_sc_hd__inv_2 fopt17321(.A (n_722), .Y (n_723));
  sky130_fd_sc_hd__nand3_2 g104(.A (n_493), .B (n_26), .C (n_617), .Y
       (n_722));
  sky130_fd_sc_hd__inv_2 g105(.A (n_609), .Y (n_517));
  sky130_fd_sc_hd__and3b_1 g98(.A_N (n_726), .B (n_542), .C (n_50), .X
       (n_727));
  sky130_fd_sc_hd__nand2_2 g100(.A (n_723), .B (n_517), .Y (n_726));
  sky130_fd_sc_hd__nand4_1 g99(.A (n_567), .B (n_728), .C (n_517), .D
       (n_493), .Y (n_729));
  sky130_fd_sc_hd__and3_1 g101(.A (n_26), .B (n_617), .C (n_362), .X
       (n_728));
  sky130_fd_sc_hd__or2_1 g97(.A (n_540), .B (n_726), .X (n_730));
  sky130_fd_sc_hd__nand3_1 g17322(.A (n_749), .B (n_952), .C (n_742),
       .Y (n_733));
  sky130_fd_sc_hd__nand2_2 g17324(.A (n_88), .B (n_642), .Y (n_731));
  sky130_fd_sc_hd__nand4_1 g60(.A (n_740), .B (n_216), .C (n_257), .D
       (n_645), .Y (n_735));
  sky130_fd_sc_hd__nand2_1 g17327(.A (n_740), .B (n_216), .Y (n_737));
  sky130_fd_sc_hd__nand2_2 g49(.A (n_758), .B (n_88), .Y (n_740));
  sky130_fd_sc_hd__nand2_2 g17329(.A (n_774), .B (n_74), .Y (n_738));
  sky130_fd_sc_hd__nand2_1 g50(.A (n_257), .B (n_758), .Y (n_741));
  sky130_fd_sc_hd__nand2b_1 g17330(.A_N (n_758), .B (n_257), .Y
       (n_742));
  sky130_fd_sc_hd__nand2_1 g22(.A (n_744), .B (n_735), .Y (n_745));
  sky130_fd_sc_hd__nand2_1 g23(.A (n_956), .B (a_reg[3]), .Y (n_744));
  sky130_fd_sc_hd__nand3_1 g45(.A (n_952), .B (n_741), .C (n_747), .Y
       (n_748));
  sky130_fd_sc_hd__o21ba_1 g46(.A1 (n_330), .A2 (n_746), .B1_N (n_88),
       .X (n_747));
  sky130_fd_sc_hd__nand2_1 g48(.A (n_559), .B (n_55), .Y (n_746));
  sky130_fd_sc_hd__a21oi_2 g47(.A1 (n_746), .A2 (n_35), .B1 (n_731), .Y
       (n_749));
  sky130_fd_sc_hd__nand2_1 g93(.A (n_753), .B (n_50), .Y (n_754));
  sky130_fd_sc_hd__nand3_1 g94(.A (n_324), .B (n_957), .C (n_752), .Y
       (n_753));
  sky130_fd_sc_hd__nand2b_1 g17331(.A_N (n_550), .B (n_436), .Y
       (n_752));
  sky130_fd_sc_hd__nand2_2 g78(.A (n_738), .B (n_757), .Y (n_758));
  sky130_fd_sc_hd__nand2_2 g81(.A (n_756), .B (b_reg[1]), .Y (n_757));
  sky130_fd_sc_hd__inv_2 g82(.A (n_755), .Y (n_756));
  sky130_fd_sc_hd__clkinv_2 g84(.A (a_reg[1]), .Y (n_755));
  sky130_fd_sc_hd__nand4b_1 g77(.A_N (n_757), .B (n_363), .C (n_780),
       .D (n_289), .Y (n_759));
  sky130_fd_sc_hd__nand4bb_1 g76(.A_N (n_776), .B_N (n_757), .C
       (n_363), .D (n_376), .Y (n_760));
  sky130_fd_sc_hd__nand2_1 g79(.A (n_623), .B (n_756), .Y (n_761));
  sky130_fd_sc_hd__nand2_1 g80(.A (b_reg[1]), .B (n_755), .Y (n_762));
  sky130_fd_sc_hd__inv_2 g83(.A (n_755), .Y (n_436));
  sky130_fd_sc_hd__nand3_1 g17333(.A (n_654), .B (n_765), .C (n_165),
       .Y (n_766));
  sky130_fd_sc_hd__nand2_1 g17334(.A (n_691), .B (n_118), .Y (n_765));
  sky130_fd_sc_hd__nand3_2 g34(.A (n_768), .B (n_419), .C (n_35), .Y
       (n_769));
  sky130_fd_sc_hd__inv_2 g35(.A (n_767), .Y (n_768));
  sky130_fd_sc_hd__nand3_2 g36(.A (n_560), .B (n_213), .C (n_214), .Y
       (n_767));
  sky130_fd_sc_hd__nand2_2 g8(.A (n_771), .B (a_reg[0]), .Y (n_772));
  sky130_fd_sc_hd__inv_2 g9(.A (n_770), .Y (n_771));
  sky130_fd_sc_hd__inv_2 g10(.A (n_47), .Y (n_770));
  sky130_fd_sc_hd__nand2_2 g17335(.A (n_773), .B (n_774), .Y (n_775));
  sky130_fd_sc_hd__and2_4 g17336(.A (n_327), .B (n_362), .X (n_773));
  sky130_fd_sc_hd__nand2_2 g17337(.A (n_617), .B (n_755), .Y (n_774));
  sky130_fd_sc_hd__inv_2 fopt17338(.A (n_777), .Y (n_776));
  sky130_fd_sc_hd__clkinv_2 fopt17340(.A (n_779), .Y (n_780));
  sky130_fd_sc_hd__buf_4 fopt17342(.A (n_39), .X (n_779));
  sky130_fd_sc_hd__inv_4 fopt17345(.A (n_39), .Y (n_777));
  sky130_fd_sc_hd__nand4_1 g2(.A (n_517), .B (n_14), .C (n_459), .D
       (n_436), .Y (n_787));
  sky130_fd_sc_hd__inv_1 drc_bufs(.A (n_801), .Y (n_799));
  sky130_fd_sc_hd__inv_1 drc_bufs17357(.A (n_536), .Y (n_801));
  sky130_fd_sc_hd__and3_1 g17506(.A (n_497), .B (n_953), .C (n_292), .X
       (n_952));
  sky130_fd_sc_hd__nand4b_1 g17507(.A_N (n_376), .B (n_776), .C (n_50),
       .D (n_327), .Y (n_953));
  sky130_fd_sc_hd__o211a_1 g17508(.A1 (n_550), .A2 (n_234), .B1
       (n_480), .C1 (n_248), .X (n_954));
  sky130_fd_sc_hd__o21ai_1 g17509(.A1 (n_237), .A2 (n_771), .B1
       (n_555), .Y (n_955));
  sky130_fd_sc_hd__nand3_1 g17510(.A (n_98), .B (n_93), .C (n_550), .Y
       (n_956));
  sky130_fd_sc_hd__nand3b_1 g17511(.A_N (n_99), .B (n_459), .C (n_376),
       .Y (n_957));
  sky130_fd_sc_hd__and2_1 g17548(.A (n_777), .B (op_reg[1]), .X
       (n_994));
  sky130_fd_sc_hd__or2_1 g17549(.A (a_reg[3]), .B (n_602), .X (n_995));
endmodule

